FC=gfortran
FFLAGS=-Wall -std=f2018 -fimplicit-none -Wno-maybe-uninitialized -Wno-unused-function -static-libgfortran -flto
FOPT=-O3 -ftree-vectorize -fopt-info-vec -fopenmp

all:          
	$(FC) $(FFLAGS) $(FOPT) -c src/environment.f90 -J obj/ -o obj/environment.o
	$(FC) $(FFLAGS) $(FOPT) -c src/config.f90 -J obj/ -o obj/config.o
	$(FC) $(FFLAGS) $(FOPT) -c src/io_process.f90 -J obj/ -o obj/io_process.o
	$(FC) $(FFLAGS) $(FOPT) -c src/process.f90 -J obj/ -o obj/process.o
	$(FC) $(FFLAGS) $(FOPT) -c src/main.f90 -I obj/ -o obj/main.o
	$(FC) $(FFLAGS) $(FOPT) -o bin/app obj/environment.o obj/config.o obj/io_process.o obj/process.o obj/main.o

clean:
	rm -rf obj/*            
	rm -rf bin/*

run:
	clear
	cd ./bin; ./app;
	head -n 10 bin/output.txt
	tail -n 10 bin/output.txt
